### ISSUE TITLE
The gar_match app does not match properly

### ISSUE THREAD

**Issue by ruochunjin** [MinovskySociety/dmine-pro#4]
[gar_match_test.zip](https://github.com/MinovskySociety/dmine-pro/files/8355272/gar_match_test.zip)

I have written a test case where there is only one edge in the data graph and one edge in the GAR pattern. However, the gar_match finds no matches. Is it the problem of loading data or my mannual test case is incorrect? 

The data and configuration files are attached in the zip file.

**Comment by F-wz** [comment]
Illegal yaml file, should be configured as:

```yaml
Graph:
  Name: test_graph
  Dir: ./gar_match_test/
  VertexFile:
    - g_v.csv
  EdgeFile:
    - g_e.csv

GAR:
  Name: gar_1
  Dir: ./gar_match_test/
  VertexFile: gar_1_p_v.csv
  EdgeFile: gar_1_p_e.csv
  LiteralX: gar_1_x_l.csv
  LiteralY: gar_1_y_l.csv

ResultDir: ./gar_match_test/result/
```
Both g_e.csv and g_v.csv are also illegal, should be corrected as:

g_v.csv:
```
vertex_id:int,label_id:int
0,0
1,0
```

g_e.csv:
```
edge_id:int,source_id:int,target_id:int,label_id:int
0,0,1,0
1,1,0,0
```

out put result: 
```
match_id,0,1
1,0,1
2,1,0
```

see attached file: 
[gar_match_test.zip](https://github.com/MinovskySociety/dmine-pro/files/8355712/gar_match_test.zip)
